services:
  app:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 5050 --reload
    volumes:
      - .:/src
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/dev
      DATABASE_URL_SYNC: postgresql://postgres:postgres@db:5432/dev
    env_file:
      - ./.env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic:
    build: .
    command: alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/dev
      DATABASE_URL_SYNC: postgresql://postgres:postgres@db:5432/dev
    env_file:
      - ./.env

volumes:
  postgres_data:
